### ISSUE TITLE
Xcode 12.4 & mac OS Big Sur: Not found in Xcode's Editor menu

### ISSUE THREAD

**Issue by yujif** [sidepelican/AddNextEx#2]
After setting up with the release build (1.1), I had the following problems.

### Environment
- https://github.com/sidepelican/AddNextEx/releases/tag/1.1
    - 👀 https://github.com/sidepelican/AddNextEx#easy-way
- macOS Big Sur 11.2.3 (20D91)
- Xcode 12.4 (12D4e)

### Problem
- The menu-item `AddNextEx` is not added to Xcode's Editor menu. 😢 
    - I've restarted Xcode and macOS, but nothing has changed.
    - I also made sure that the extension was enabled in System Preferences.
   
### Solution
- I added `XcodeKit.framework` (Embed & Sign) and built it myself, and now it is added to the menu 🎉 
    - Ref: https://developer.apple.com/forums/thread/666434?answerId=662924022#662924022

## Proposal
- Add `XcodeKit.framework` (Embed & Sign) and release new build

**Comment by sidepelican** [comment]
@yujif  Thanks for reporting and finding solution. great!
But I need to tell you an important thing...

Open your Xcode and open `Find` menu, and select `Select Next Occurrence` or `Select Previous Occurrence`.
The function provided by this extension was already implemented in the latest Xcode😆.

This extension has already served its duty!

**Comment by sidepelican** [comment]
Update README.md.
